// Phrase pools. "pt" is shown for visitors detected in Brazil, "en" otherwise.
const PHRASES = {
  pt: [
    "Desista. Ninguém vai notar a diferença.",
    "O esforço é opcional. O fracasso, garantido.",
    "Você não está atrasado. Só é irrelevante mais cedo.",
    "Sonhos são só planos que ainda não deram errado.",
    "Nem toda ideia ruim é sua, mas a maioria é.",
    "Trabalho em equipe: quando seu erro vira responsabilidade de todos.",
    "Acredite em si mesmo. Os outros já desistiram de você.",
    "Grandes conquistas vêm para quem espera. Na verdade, as vezes não.",
    "Roma não foi construída em um dia, mas caiu em uma tarde.",
    "O único limite é a sua imaginação. E o seu talento. E o seu orçamento.",
    "Mire nas estrelas. Aceite o teto.",
    "O sucesso é uma jornada, não um destino. Você não vai chegar.",
    "Tudo tem um lado bom, exceto pra você, neste caso é só lado ruim.",
    "Finja até conseguir. A maioria nunca consegue e finge pelo resto da vida.",
    "O fracasso não é o oposto do sucesso. Muito pelo contrário.",
    "Siga sua paixão até o desemprego.",
    "Essa reunião podia ter sido um e-mail. Sua ideia também.",
    "Corra atrás dos seus sonhos. Mas saiba que dificilmente você vai alcançá-los.",
  ],
  en: [
    "Give up. No one will notice the difference.",
    "Dreams are just plans that haven't failed yet.",
    "You're not behind. You're just early to irrelevance.",
    "Not every bad idea is yours, but most are.",
    "Teamwork: when your mistake becomes everyone's problem.",
    "Effort is optional. Disappointment is not.",
    "Believe in yourself. Everyone else has already stopped.",
    "Great things come to those who wait. Actually, sometimes they dont.",
    "Rome wasn't built in a day, but it did eventually fall.",
    "The only limit is your imagination. And your talent. And your budget.",
    "Reach for the stars. Settle for the ceiling.",
    "Success is a journey, not a destination. You will not be arriving.",
    "Every cloud has a silver lining. This one's just rain.",
    "Fake it till you make it. Most people never make it.",
    "Failure is not the opposite of success. It's just success running late.",
    "Follow your passion, straight into unemployment.",
    "Meetings could have been an email. So could most of your ideas.",
    "Chase your dreams. They have a head start.",
  ],
};

// Fallback backgrounds, used only if images/manifest.json can't be loaded
// (e.g. no images added yet). The real list is generated by
// scripts/generate-manifest.sh from whatever is in images/ — drop files
// there and re-run the script, no code edits needed.
const FALLBACK_BACKGROUNDS = [
  "linear-gradient(135deg, #232526, #414345)",
  "linear-gradient(135deg, #0f2027, #203a43, #2c5364)",
  "linear-gradient(135deg, #3a1c71, #d76d77, #ffaf7b)",
];

// Fonts to randomize between on each load. Loaded via the Google Fonts
// link in index.html — add a font here AND to that link's URL together.
const FONTS = [
  {
    family: "'Playfair Display', Georgia, serif",
    weight: 700,
    style: "normal",
    letterSpacing: "0.01em",
  },
  {
    family: "'Bebas Neue', sans-serif",
    weight: 400,
    style: "normal",
    letterSpacing: "0.05em",
  },
  {
    family: "'Cormorant Garamond', Georgia, serif",
    weight: 600,
    style: "italic",
    letterSpacing: "0.01em",
  },
  {
    family: "'Abril Fatface', Georgia, serif",
    weight: 400,
    style: "normal",
    letterSpacing: "0.005em",
  },
  {
    family: "'IBM Plex Mono', monospace",
    weight: 600,
    style: "normal",
    letterSpacing: "0",
  },
  {
    family: "'Oswald', sans-serif",
    weight: 600,
    style: "normal",
    letterSpacing: "0.02em",
  },
  {
    family: "'Anton', sans-serif",
    weight: 400,
    style: "normal",
    letterSpacing: "0.02em",
  },
  {
    family: "'Libre Baskerville', Georgia, serif",
    weight: 400,
    style: "normal",
    letterSpacing: "0.005em",
  },
  {
    family: "'Permanent Marker', cursive",
    weight: 400,
    style: "normal",
    letterSpacing: "0.01em",
  },
  {
    family: "'Pirata One', serif",
    weight: 400,
    style: "normal",
    letterSpacing: "0.01em",
  },
];
