// Phrase pools. "pt" is shown for visitors detected in Brazil, "en" otherwise.
const PHRASES = {
  pt: [
    "Desista. Ninguém vai notar a diferença.",
    "O esforço é opcional. O fracasso, garantido.",
    "Você não está atrasado. Só é irrelevante mais cedo.",
    "Sonhos são só planos que ainda não deram errado.",
    "Nem toda ideia ruim é sua, mas a maioria é.",
    "Trabalho em equipe: quando seu erro vira responsabilidade de todos.",
    "Acredite em si mesmo. Os outros já desistiram de você.",
    "Grandes conquistas vêm para quem espera. Na verdade, às vezes não.",
    "Roma não foi construída em um dia, mas caiu em uma tarde.",
    "O único limite é a sua imaginação. E o seu talento. E o seu orçamento.",
    "Mire nas estrelas. Aceite o teto.",
    "O sucesso é uma jornada, não um destino. Você não vai chegar.",
    "Tudo tem um lado bom, exceto pra você. Neste caso é só lado ruim.",
    "Finja até conseguir. A maioria nunca consegue e finge pelo resto da vida.",
    "O fracasso não é o oposto do sucesso. Muito pelo contrário.",
    "Siga sua paixão até o desemprego.",
    "Essa reunião podia ter sido um e-mail. Sua ideia também.",
    "Corra atrás dos seus sonhos. Mas saiba que dificilmente você vai alcançá-los.",
    "O fundo do poço também tem subsolo.",
    "Sempre há alguém melhor que você. Provavelmente ao seu lado.",
    "A persistência leva ao sucesso. Às vezes leva só ao cansaço.",
    "Não deixe para amanhã o fracasso que você pode ter hoje.",
    "Você é único. Assim como bilhões de outras pessoas.",
    "A vida é feita de escolhas erradas. As certas são coincidência.",
    "Nunca é tarde para desistir.",
    "Continue tentando. Você ainda não falhou de todas as maneiras possíveis.",
    "Se tudo parece fácil, você provavelmente entendeu errado.",
    "O impossível só demora um pouco mais para dar errado.",
    "Seu potencial é ilimitado. Sua disposição nem tanto.",
    "A experiência é o nome que damos aos nossos erros repetidos.",
    "Você pode ser qualquer coisa. Desde que seja mediano.",
    "Nem todo atalho leva ao destino. Alguns só economizam esperança.",
    "A motivação acaba. As contas não.",
    "O importante é competir. Perder é consequência.",
    "Se ninguém acredita em você, pelo menos existe consistência.",
    "O universo não conspira. Ele só ignora.",
    "Toda oportunidade parece boa antes de virar problema.",
    "O talento abre portas. O azar fecha todas elas.",
    "O plano era perfeito. A realidade discordou.",
    "O fracasso também é uma forma de consistência.",
    "O sucesso é relativo. O boleto é absoluto.",
    "A esperança é a última que morre. Mas também morre.",
    "Seu pior crítico provavelmente está certo.",
    "O importante é aprender com os erros. Você terá bastante prática.",
    "Algumas pessoas nasceram para brilhar. Outras para segurar a lanterna.",
    "O mundo não gira ao seu redor. Ele mal percebe que você existe.",
    "Quanto maior a expectativa, maior a decepção.",
    "Você merece o melhor. Pena que merece não significa recebe.",
    "Se o plano A falhar, ainda existem mais 25 letras para dar errado.",
    "O tempo cura tudo. Exceto vergonha alheia.",
    "Você é um personagem secundário na história de alguém mais interessante.",
    "O segundo rato é que pega o queijo. O primeiro pega a ratoeira.",
    "O prego que se destaca é o primeiro a levar martelada.",
    "A esperança é o primeiro passo no caminho da decepção.",
    "As punições vão continuar até o moral melhorar.",
    "Às vezes a melhor solução pra moral baixa é demitir todo mundo insatisfeito.",
    "A única coisa em comum entre todos os seus fracassos é você.",
    "Nem todo mundo pode ser astronauta.",
    "É sempre mais escuro pouco antes de ficar completamente breu.",
    "Quando você erra, ninguém esquece. Quando acerta, ninguém lembra.",
    "Sempre tem alguém na internet que faz melhor que você.",
    "Quem desiste nunca perde, e quem trapaceia sempre ganha.",
    "Felicidade é só tristeza que ainda não aconteceu.",
    "Quem importa não liga. Quem liga não importa.",
    "Ninguém é especial.",
    "Você nunca vai lembrar dos seus sucessos tanto quanto dos seus fracassos.",
    "Se não conseguir de primeira, tente algo mais fácil.",
    "O mundo está aos seus pés. Uma pena que você tropeça em tudo.",
    "Nenhum de nós é tão burro quanto todos nós juntos.",
    "Nunca subestime o poder de gente burra em grande quantidade.",
    "Não importa se o copo está meio cheio ou meio vazio: a quantidade de água é a mesma.",
    "O que não te mata às vezes te faz desejar que tivesse matado."
  ],
  en: [
    "Give up. No one will notice the difference.",
    "Effort is optional. Failure is guaranteed.",
    "You're not behind. You're just early to irrelevance.",
    "Dreams are just plans that haven't failed yet.",
    "Not every bad idea is yours, but most are.",
    "Teamwork: when your mistake becomes everyone's responsibility.",
    "Believe in yourself. Everyone else has already stopped.",
    "Great things come to those who wait. Actually, sometimes they don't.",
    "Rome wasn't built in a day, but it did eventually fall.",
    "The only limit is your imagination. And your talent. And your budget.",
    "Reach for the stars. Settle for the ceiling.",
    "Success is a journey, not a destination. You will not be arriving.",
    "Everything has a bright side. This isn't one of those times.",
    "Fake it till you make it. Most people never make it.",
    "Failure is not the opposite of success. Quite the opposite.",
    "Follow your passion, straight into unemployment.",
    "Meetings could have been an email. So could most of your ideas.",
    "Chase your dreams. They have a head start.",
    "Rock bottom has a basement.",
    "There's always someone better than you. Probably sitting next to you.",
    "Persistence leads to success. Sometimes it just leads to exhaustion.",
    "Don't put off until tomorrow the failure you can have today.",
    "You're unique. Just like billions of other people.",
    "Life is made of bad decisions. The good ones are mostly accidents.",
    "It's never too late to quit.",
    "Keep trying. You haven't failed in every possible way yet.",
    "If everything seems easy, you've probably misunderstood something.",
    "The impossible just takes a little longer to fail.",
    "Your potential is limitless. Your motivation isn't.",
    "Experience is what we call our repeated mistakes.",
    "You can be anything. As long as it's average.",
    "Not every shortcut leads somewhere. Some just save you hope.",
    "Motivation ends. Bills don't.",
    "The important thing is to compete. Losing is just the outcome.",
    "If nobody believes in you, at least there's consistency.",
    "The universe isn't conspiring. It just doesn't care.",
    "Every opportunity looks great before it becomes a problem.",
    "Talent opens doors. Bad luck closes them all.",
    "The plan was perfect. Reality disagreed.",
    "Failure is also a form of consistency.",
    "Success is relative. Bills are absolute.",
    "Hope is the last to die. It still dies.",
    "Your worst critic is probably right.",
    "The important thing is to learn from your mistakes. You'll get plenty of practice.",
    "Some people were born to shine. Others were born to hold the flashlight.",
    "The world doesn't revolve around you. It barely notices you exist.",
    "The higher the expectations, the greater the disappointment.",
    "You deserve the best. Too bad deserving doesn't mean getting it.",
    "If Plan A fails, there are 25 more letters to fail with.",
    "Time heals everything. Except secondhand embarrassment.",
    "You are a background character in someone else's more interesting story.",
    "The second mouse gets the cheese.",
    "The nail that sticks out gets hammered first.",
    "Hope is the first step on the road to disappointment.",
    "The beatings will continue until morale improves.",
    "Sometimes the best solution to morale problems is firing all the unhappy people.",
    "The only thing all your failures have in common is you.",
    "Not everyone can be an astronaut.",
    "It's always darkest just before it goes pitch black.",
    "When you do bad, no one forgets. When you do good, no one remembers.",
    "There's always someone on the internet who can do it better than you.",
    "Quitters never lose, and cheaters always win.",
    "Happiness is just sadness that hasn't happened yet.",
    "No one who matters cares. No one who cares matters.",
    "Nobody's special.",
    "You'll never remember your successes as much as your failures.",
    "If at first you don't succeed, try something easier.",
    "The world is your oyster. Too bad you're allergic to seafood.",
    "None of us is as dumb as all of us.",
    "Never underestimate the power of stupid people in large groups.",
    "You shouldn't care whether the glass is half full or half empty — it's the same amount of water either way.",
    "What doesn't kill you sometimes just makes you wish it had."
  ],
};

// Fallback backgrounds, used only if images/manifest.json can't be loaded
// (e.g. no images added yet). The real list is generated by
// scripts/generate-manifest.sh from whatever is in images/ — drop files
// there and re-run the script, no code edits needed.
const FALLBACK_BACKGROUNDS = [
  "linear-gradient(135deg, #232526, #414345)",
  "linear-gradient(135deg, #0f2027, #203a43, #2c5364)",
  "linear-gradient(135deg, #3a1c71, #d76d77, #ffaf7b)",
];

// Fonts to randomize between on each load. Loaded via the Google Fonts
// link in index.html — add a font here AND to that link's URL together.
const FONTS = [
  {
    family: "'Playfair Display', Georgia, serif",
    weight: 700,
    style: "normal",
    letterSpacing: "0.01em",
  },
  {
    family: "'Bebas Neue', sans-serif",
    weight: 400,
    style: "normal",
    letterSpacing: "0.05em",
  },
  {
    family: "'Cormorant Garamond', Georgia, serif",
    weight: 600,
    style: "italic",
    letterSpacing: "0.01em",
  },
  {
    family: "'Abril Fatface', Georgia, serif",
    weight: 400,
    style: "normal",
    letterSpacing: "0.005em",
  },
  {
    family: "'IBM Plex Mono', monospace",
    weight: 600,
    style: "normal",
    letterSpacing: "0",
  },
  {
    family: "'Oswald', sans-serif",
    weight: 600,
    style: "normal",
    letterSpacing: "0.02em",
  },
  {
    family: "'Anton', sans-serif",
    weight: 400,
    style: "normal",
    letterSpacing: "0.02em",
  },
  {
    family: "'Libre Baskerville', Georgia, serif",
    weight: 400,
    style: "normal",
    letterSpacing: "0.005em",
  },
  {
    family: "'Permanent Marker', cursive",
    weight: 400,
    style: "normal",
    letterSpacing: "0.01em",
  },
  {
    family: "'Pirata One', serif",
    weight: 400,
    style: "normal",
    letterSpacing: "0.01em",
  },
];
